print("jangan takut, saya gk gigit")
print("jangan lari kalian")
print("jangan lupa ibadah")
print("halo kalian semua")
print("ko kamu lucu si")
print("jangan lupa senyumm")
print("cape ya?sama ko aku juga")
print("tetap menyerah jangan semangat")
print("hargailah jika kamu mau dihargai")
print("semangat yu kaliam pasti bisa")